# Generated by Django 3.0.1 on 2020-09-10 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult_subject_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_year',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_result_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
