# Generated by Django 3.0.1 on 2020-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_remove_students_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_year',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
