# Generated by Django 3.0.1 on 2020-09-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_students_class_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_year',
        ),
    ]
