# Generated by Django 3.0.1 on 2020-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_remove_students_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
