# Generated by Django 3.1.4 on 2020-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_auto_20200914_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_exam_marks',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
